name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Coverage
        uses: codecov/codecov-action@v1

      - name: Setup
        run: |
          docker-compose up -d
          sudo npm link

      - name: E2E
        run: |
          ssc pull -c ./docker/config.json
          npm run e2e:docker
