name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: npm run build
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Setup
        run: docker-compose up -d

      - name: Startup
        run: sudo ./docker/wait.sh

      - name: Restore
        shell: pwsh
        run: .\docker\restore.ps1

      - name: Build
        run: |
          npm run build
          sudo npm link

      - name: Test
        run: |
          ssc pull -c ./docker/config.json
          npm run e2e:docker
