name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Coverage
        uses: codecov/codecov-action@v1
  e2e:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Setup
        shell: pwsh
        run: |
          docker-compose up -d
          npm run build
          npm link
          ssc pull -c ./docker/config.json

      - name: Test
        run: npm run e2e:docker
